MACRO( GET_PROJECT PROJ )
  include( ${PROJ} )

  MESSAGE( STATUS "Downloading or verifying ${ARCHIVE_NAME_WE}" )
  FILE( DOWNLOAD ${ARCHIVE_URL}
    "${CMAKE_CURRENT_BINARY_DIR}/${ARCHIVE_NAME}"
    SHOW_PROGRESS EXPECTED_MD5 ${ARCHIVE_MD5}
    )

  if( "${CMAKE_CURRENT_BINARY_DIR}/${ARCHIVE_NAME}" IS_NEWER_THAN "${CMAKE_CURRENT_BINARY_DIR}${ARCHIVE_NAME_WE}" )
    MESSAGE( STATUS "Extracting ${ARCHIVE_NAME_WE}" )

    EXECUTE_PROCESS(
      COMMAND "${CMAKE_COMMAND}" -E
      tar -xf "${CMAKE_CURRENT_BINARY_DIR}/${ARCHIVE_NAME}"
      WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}"
      )

    FILE( WRITE
      "${CMAKE_CURRENT_BINARY_DIR}/${ARCHIVE_NAME_WE}/CMakeLists.txt"
      ${PROJECT_CMAKELISTS}
      )

    ADD_SUBDIRECTORY(
      "${CMAKE_CURRENT_BINARY_DIR}/${ARCHIVE_NAME_WE}"
      )
  endif ()

  unset( ARCHIVE_URL )
  unset( ARCHIVE_MD5 )
  unset( ARCHIVE_NAME )
  unset( ARCHIVE_NAME_WE )
  unset( PROJECT_CMAKELISTS )
ENDMACRO( GET_PROJECT )